# Generated by Django 4.1.7 on 2023-03-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_customer', models.CharField(max_length=200, unique=True)),
                ('ced_ruc', models.IntegerField(max_length=15)),
                ('description_customer', models.TextField(blank=True, max_length=500)),
                ('email_customer', models.CharField(blank=True, max_length=50)),
                ('direction', models.TextField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
