# Generated by Django 4.1.7 on 2023-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ced_ruc',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
